id = "gruvbox-material-neovim"
name = "Gruvbox Material Neovim"
version = "1.0.0"
schema_version = 1
authors = ["RiverMatsumoto"]
description = "Gruvbox Material port from f4z3r's gruvbox-material.nvim palette. Their work can be found at https://github.com/f4z3r/gruvbox-material.nvim/tree/master"
repository = "https://github.com/RiverMatsumoto/gruvbox-material-nvim-zed"
